/**
 * API Contract Types for Agent Operations
 *
 * These types define the request/response shapes for the three agent endpoints:
 * - chat-message: Simple chat interaction
 * - chat-execute: Chat with execution mode
 * - agent-run: Full agent execution with analysis and reporting options
 */

// Enum-like types for form options
export type AnalysisType = 'none' | 'structural' | 'code' | 'comprehensive'
export type ReportFormat = 'markdown' | 'html' | 'json'
export type ReportOutput = 'inline' | 'file' | 'both'
export type ConnectionState = 'disconnected' | 'connecting' | 'connected' | 'error'

/**
 * Context payload shared across request types
 */
export interface ContextPayload {
  /** Optional model JSON text to include in request */
  modelText?: string
  /** Whether to include the model in the context */
  includeModel?: boolean
}

/**
 * Request payload for chat-message endpoint
 * Simple chat interaction without execution
 */
export interface ChatMessageRequest {
  /** The user's message text */
  message: string
  /** Optional conversation ID for continuity */
  conversationId?: string | null
  /** Optional trace ID for request tracking */
  traceId?: string | null
  /** Optional context payload */
  context?: ContextPayload
}

/**
 * Request payload for chat-execute endpoint
 * Chat with execution mode (mode is required)
 */
export interface ChatExecuteRequest {
  /** The user's message text */
  message: string
  /** Execution mode: chat, execute, or auto */
  mode: 'chat' | 'execute' | 'auto'
  /** Optional conversation ID for continuity */
  conversationId?: string | null
  /** Optional trace ID for request tracking */
  traceId?: string | null
  /** Optional context payload */
  context?: ContextPayload
}

/**
 * Request payload for agent-run endpoint
 * Full agent execution with analysis and reporting options
 */
export interface AgentRunRequest {
  /** The user's message text */
  message: string
  /** Execution mode: chat, execute, or auto */
  mode: 'chat' | 'execute' | 'auto'
  /** Optional conversation ID for continuity */
  conversationId?: string | null
  /** Optional trace ID for request tracking */
  traceId?: string | null
  /** Optional context payload */
  context?: ContextPayload
  /** Type of analysis to perform */
  analysisType?: AnalysisType
  /** Format for report output */
  reportFormat?: ReportFormat
  /** Where to output the report */
  reportOutput?: ReportOutput
  /** Whether to auto-analyze results */
  autoAnalyze?: boolean
  /** Whether to perform automatic code checking */
  autoCodeCheck?: boolean
  /** Whether to include a report in the response */
  includeReport?: boolean
}

/**
 * Artifact from agent execution
 */
export interface Artifact {
  /** Format of the artifact */
  format: string
  /** Path to the artifact */
  path: string
}

/**
 * Agent execution result
 */
export interface AgentResult {
  /** The agent's response text */
  response: string
  /** Conversation ID for continuity */
  conversationId?: string
  /** Trace ID for request tracking */
  traceId?: string
  /** Optional structured data from the agent */
  data?: Record<string, unknown>
  /** Artifacts generated by the agent */
  artifacts?: Artifact[]
}

/**
 * Agent error response
 */
export interface AgentError {
  /** Error message */
  message: string
  /** Optional error code */
  code?: string
  /** Optional additional details */
  details?: Record<string, unknown>
}

/**
 * Stream frame types for SSE responses
 */
export type StreamFrameType = 'text' | 'tool_call' | 'clarification' | 'complete' | 'error'

/**
 * Stream frame for SSE responses
 */
export interface StreamFrame {
  /** Type of stream frame */
  type: StreamFrameType
  /** Content of the frame */
  content: string | Record<string, unknown>
  /** Optional timestamp */
  timestamp?: string
}

/**
 * Agent metrics from execution
 */
export interface AgentMetrics {
  /** Total tokens used */
  totalTokens?: number
  /** Prompt tokens used */
  promptTokens?: number
  /** Completion tokens used */
  completionTokens?: number
  /** Execution time in milliseconds */
  executionTimeMs?: number
}

/**
 * Agent tool call information
 */
export interface AgentToolCall {
  /** Tool name */
  name: string
  /** Tool arguments */
  arguments: Record<string, unknown>
  /** Optional result from tool execution */
  result?: unknown
}

/**
 * Clarification request from agent
 */
export interface Clarification {
  /** Clarification ID */
  id: string
  /** Question text */
  question: string
  /** Optional options for the user to choose from */
  options?: string[]
}
